spring:
  config:
    import: application-secret.properties
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DATA_SOURCE_URL}
    username: ${DATA_SOURCE_USER_NAME}
    password: ${DATA_SOURCE_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      dialect: org.hibernate.dialect.MySQL8Dialect
    properties:
      format_sql: true
      show_sql: true
